### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/yaus#10]
Document the steps in Gitpod installation script in the readme.

**Comment by tushar5526** [comment]
I am starting with this.

**Comment by tushar5526** [comment]
I am thinking of making a Makefile for easy setup.

Makefile will have the following targets.

`Install and Run`: Install nvm, unzip data etc.
`Run`: Running docker-compose and other services
`Stop`: Does what the name says 
`Reset`: Removes all the stopped containers and starts new containers, for cases, there were changes to the env file that has to be picked up.

Readme will explain these targets, instead of the steps.

**Comment by ChakshuGautam** [comment]
Makefiles are very C specific - and may lead to some confusion. We should create a `cli` that allows to do the same though.

**Comment by ChakshuGautam** [comment]
Let's start with a makefile only.

**Comment by tushar5526** [comment]
> Makefiles are very C specific - and may lead to some confusion. We should create a `cli` that allows to do the same though. The cli can be used for other purposes as well - like creating urls etc.

Yes, it will be a good addition that we can work on later.
